import { format, parseISO } from 'date-fns';
import blogData from '../data/blogData.json';
import { SERIES } from '../data/series';
import booksData from '../data/booksData.json';

export const BLOG_CONFIG = {
  categories: {
    curiosities: {
      name: 'Mathematical Curiosities',
      description: 'Explorations of games, puzzles, and mathematical phenomena',
      // Brand v2: single accent (cyan). Keep `color` field for back-compat with any
      // consumer that still reads it, but every category resolves to the same accent.
      color: 'cyan',
      icon: 'Brain'
    },
    research: {
      name: 'Research Notes',
      description: 'Academic papers, studies, and research insights',
      color: 'cyan',
      icon: 'FileText'
    },
    'field-notes': {
      name: 'Field Notes',
      description: 'Practical guides and technical deep-dives from real-world ML/AI work',
      color: 'cyan',
      icon: 'Code2'
    }
  },
  /** Mobile/tablet (< Tailwind lg): 2 cols at md, 1 col default */
  postsPerPageMobile: 6,
  /** Desktop (≥1024px, lg: 3-column grid) */
  postsPerPageDesktop: 9
};

export async function loadAllPosts() {
  try {
    return blogData.posts || [];
  } catch (error) {
    console.error('Error loading blog posts:', error);
    return [];
  }
}

export async function getPostBySlug(category, slug) {
  try {
    const allPosts = await loadAllPosts();
    const post = allPosts.find(p => p.category === category && p.slug === slug);
    return post || null;
  } catch (error) {
    console.error(`Error loading post ${category}/${slug}:`, error);
    return null;
  }
}

export async function getPostsByCategory(category) {
  try {
    const allPosts = await loadAllPosts();
    return allPosts.filter(post => post.category === category);
  } catch (error) {
    console.error(`Error loading posts for category ${category}:`, error);
    return [];
  }
}

export async function getPostsByTag(tag) {
  try {
    const allPosts = await loadAllPosts();
    return allPosts.filter(post => 
      post.tags && post.tags.some(postTag => 
        postTag.toLowerCase() === tag.toLowerCase()
      )
    );
  } catch (error) {
    console.error(`Error loading posts for tag ${tag}:`, error);
    return [];
  }
}

export async function getAllTags() {
  try {
    const allPosts = await loadAllPosts();
    const tagSet = new Set();
    
    allPosts.forEach(post => {
      if (post.tags) {
        post.tags.forEach(tag => tagSet.add(tag));
      }
    });
    
    return Array.from(tagSet).sort();
  } catch (error) {
    console.error('Error loading tags:', error);
    return [];
  }
}

/**
 * Return the curated narrative reading series (raw registry, slugs only).
 */
export async function loadAllSeries() {
  return SERIES;
}

/**
 * Resolve each series' slugs against the post catalog.
 *
 * Returns series enriched with full post objects, in declared order. Each post
 * gains `part` (1-based position) and `partsTotal`. Slugs that no longer resolve
 * to a post are dropped defensively so the page never breaks on a typo or a
 * renamed/removed post; series left with fewer than 2 resolved posts are
 * omitted entirely (a "series" of one is not a series).
 */
export async function getSeriesWithPosts() {
  try {
    const allPosts = await loadAllPosts();
    const bySlug = new Map(allPosts.map(p => [p.slug, p]));

    return SERIES.map(series => {
      const resolved = (series.posts || [])
        .map(slug => bySlug.get(slug))
        .filter(Boolean);

      const partsTotal = resolved.length;
      const posts = resolved.map((post, index) => ({
        ...post,
        part: index + 1,
        partsTotal,
      }));

      return { ...series, posts, partsTotal };
    }).filter(series => series.partsTotal >= 2);
  } catch (error) {
    console.error('Error building series with posts:', error);
    return [];
  }
}

/**
 * Return the auto-extracted books & papers index (generated by build-books.js).
 *
 * Each work carries a `count` (distinct posts citing it) and a `posts` array.
 * Defensively filters each work's posts against the live catalog so a removed
 * post never yields a dead link, and drops works left with no resolvable posts.
 */
export async function getBooksData() {
  try {
    const allPosts = await loadAllPosts();
    const known = new Set(allPosts.map((p) => p.slug));
    const resolve = (works = []) =>
      works
        .map((w) => {
          const posts = (w.posts || []).filter((p) => known.has(p.slug));
          return { ...w, posts, count: posts.length };
        })
        .filter((w) => w.count > 0)
        .sort((a, b) => b.count - a.count || a.title.localeCompare(b.title));

    const books = resolve(booksData.books);
    const papers = resolve(booksData.papers);
    return {
      books,
      papers,
      stats: {
        books: books.length,
        papers: papers.length,
        bookMentions: books.reduce((n, b) => n + b.count, 0),
        paperMentions: papers.reduce((n, p) => n + p.count, 0),
      },
    };
  } catch (error) {
    console.error('Error loading books data:', error);
    return { books: [], papers: [], stats: { books: 0, papers: 0, bookMentions: 0, paperMentions: 0 } };
  }
}

/**
 * Get the WebP version path of an image.
 * Replaces .jpg/.jpeg/.png extension with .webp.
 * Returns the original path unchanged for other formats or empty strings.
 */
export function getWebPPath(imagePath) {
  if (!imagePath) return '';
  return imagePath.replace(/\.(jpg|jpeg|png)$/i, '.webp');
}

export function formatDate(dateString, formatStr = 'MMMM d, yyyy') {
  try {
    const date = typeof dateString === 'string' ? parseISO(dateString) : dateString;
    return format(date, formatStr);
  } catch (error) {
    console.error('Error formatting date:', error);
    return dateString;
  }
}

export function slugify(text) {
  return text
    .toString()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-');
}

// Enhanced scroll function that centers the target element
export function scrollToElementCentered(elementId, options = {}) {
  const {
    offset = 0,
    navbarHeight = 80,
    behavior = 'smooth',
    updateURL = true,
    highlightElement = true
  } = options;
  
  const element = document.getElementById(elementId);
  if (!element) return false;
  
  const elementRect = element.getBoundingClientRect();
  const absoluteElementTop = elementRect.top + window.pageYOffset;
  
  // Calculate the center position accounting for navbar and custom offset
  const viewportHeight = window.innerHeight;
  const elementHeight = elementRect.height;
  
  // Center the element in the viewport
  const targetScrollTop = absoluteElementTop 
    - (viewportHeight / 2) 
    + (elementHeight / 2) 
    - (navbarHeight / 2) 
    + offset;
  
  window.scrollTo({
    top: Math.max(0, targetScrollTop),
    behavior
  });
  
  // Add highlight effect if requested
  if (highlightElement) {
    setTimeout(() => {
      element.classList.add('toc-highlight');
      setTimeout(() => {
        element.classList.remove('toc-highlight');
      }, 2000);
    }, 500);
  }
  
  // Update the URL hash after scrolling if requested
  if (updateURL) {
    setTimeout(() => {
      window.history.pushState(null, null, `#${elementId}`);
    }, 500);
  }
  
  return true;
}